#服务端口
server:
  port: 8008

spring:
  application:
    name: service-statistics #服务名


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    username: root
    password: 123456

  profiles:
    active: dev #环境配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  redis:
    host: 192.168.40.128
    password: redis2002zmlmf
    port: 6379
    database: 0
    lettuce:
      shutdown-timeout: 1800000
      pool:
        max-idle: 5 #最大阻塞等待时间(负数表示没限制)
        min-idle: 0
    jedis:
      pool:
        max-active: 20
        max-wait: -1

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#熔断器
feign:
  hystrix:
    enabled: true









