server:
  port: 8001


spring:
  application:
    name: service-edu #服务名 最好不要用下划线
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    username: root
    password: 123456

  redis:
    host: 192.168.40.128
    password: redis2002zmlmf
    port: 6379
    database: 0
    lettuce:
      shutdown-timeout: 1800000
      pool:
        max-idle: 5 #最大阻塞等待时间(负数表示没限制)
        min-idle: 0
    jedis:
      pool:
        max-active: 20
        max-wait: -1


  profiles:
    active: dev #环境设置 dev,test,pro
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #返回json的全局时间格式
    time-zone: GMT+8 #东八区
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #nacos注册中心

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #mp的日志输出策略

feign:
  hystrix:
    enabled: true #开启熔断器






